// Demo data for showcasing the save-a-stray application
// This data is used in demo mode to show potential users what the app offers

import {
  Animal,
  Shelter,
  Application,
  ApplicationStatus,
  Donation,
  ShelterEvent,
  Foster,
  Volunteer,
  BehaviorNote,
  Announcement,
  Vaccination,
  WeightRecord,
  IntakeLog,
  ActivityLogEntry,
} from "../types";

// Demo Shelter
export const demoShelter: Shelter = {
  _id: "demo-shelter-001",
  name: "Sunny Paws Rescue",
  location: "San Francisco, CA",
  paymentEmail: "donations@sunnypawsrescue.org",
  phone: "(415) 555-0123",
  email: "info@sunnypawsrescue.org",
  website: "https://sunnypawsrescue.org",
  hours: "Mon-Sat 10am-6pm, Sun 12pm-5pm",
  description: "Sunny Paws Rescue is a no-kill shelter dedicated to finding loving homes for abandoned and surrendered pets. We've been serving the Bay Area community since 2015.",
  verified: true,
  verifiedAt: "2024-01-15T00:00:00Z",
};

// Demo Animals
export const demoAnimals: Animal[] = [
  {
    _id: "demo-animal-001",
    name: "Luna",
    type: "Dogs",
    age: 2,
    breed: "Golden Retriever Mix",
    sex: "Female",
    color: "Golden",
    description: "Luna is a gentle and affectionate Golden Retriever mix who loves long walks and playing fetch. She's great with children and other dogs, making her the perfect family companion. Luna is house-trained and knows basic commands like sit, stay, and come.",
    image: "https://images.unsplash.com/photo-1633722715463-d30f4f325e24?w=600&h=600&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1552053831-71594a27632d?w=600&h=600&fit=crop",
    ],
    video: "",
    status: "available",
    shelter: {
      _id: "demo-shelter-001",
      name: "Sunny Paws Rescue",
      location: "San Francisco, CA",
    },
    medicalRecords: [
      {
        _id: "med-001",
        date: "2024-12-15",
        recordType: "Vaccination",
        description: "Rabies vaccine administered",
        veterinarian: "Dr. Sarah Chen",
      },
      {
        _id: "med-002",
        date: "2024-12-15",
        recordType: "Checkup",
        description: "Annual wellness exam - healthy",
        veterinarian: "Dr. Sarah Chen",
      },
    ],
  },
  {
    _id: "demo-animal-002",
    name: "Whiskers",
    type: "Cats",
    age: 3,
    breed: "Domestic Shorthair",
    sex: "Male",
    color: "Orange Tabby",
    description: "Whiskers is a charming orange tabby with a playful personality. He enjoys sunny windowsills, chasing feather toys, and cuddling on the couch. He's best suited for a home without small children and would prefer to be the only cat.",
    image: "https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=600&h=600&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1573865526739-10659fec78a5?w=600&h=600&fit=crop",
    ],
    video: "",
    status: "available",
    shelter: {
      _id: "demo-shelter-001",
      name: "Sunny Paws Rescue",
      location: "San Francisco, CA",
    },
    medicalRecords: [
      {
        _id: "med-003",
        date: "2024-11-20",
        recordType: "Spay/Neuter",
        description: "Neutered - recovery complete",
        veterinarian: "Dr. Michael Rodriguez",
      },
    ],
  },
  {
    _id: "demo-animal-003",
    name: "Buddy",
    type: "Dogs",
    age: 5,
    breed: "Labrador Retriever",
    sex: "Male",
    color: "Black",
    description: "Buddy is a loyal and calm black lab who would make an excellent companion for seniors or a less active household. He's well-mannered, house-trained, and loves belly rubs. Buddy gets along well with other dogs and is cat-friendly.",
    image: "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&h=600&fit=crop",
    images: [],
    video: "",
    status: "pending",
    shelter: {
      _id: "demo-shelter-001",
      name: "Sunny Paws Rescue",
      location: "San Francisco, CA",
    },
  },
  {
    _id: "demo-animal-004",
    name: "Mittens",
    type: "Cats",
    age: 1,
    breed: "Siamese Mix",
    sex: "Female",
    color: "Seal Point",
    description: "Mittens is a young and curious Siamese mix who loves to explore and play. She's very vocal and will 'talk' to you throughout the day. Mittens is litter trained and gets along well with other cats.",
    image: "https://images.unsplash.com/photo-1513245543132-31f507417b26?w=600&h=600&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1495360010541-f48722b34f7d?w=600&h=600&fit=crop",
    ],
    video: "",
    status: "available",
    shelter: {
      _id: "demo-shelter-001",
      name: "Sunny Paws Rescue",
      location: "San Francisco, CA",
    },
  },
  {
    _id: "demo-animal-005",
    name: "Max",
    type: "Dogs",
    age: 4,
    breed: "German Shepherd",
    sex: "Male",
    color: "Black and Tan",
    description: "Max is an intelligent and protective German Shepherd who needs an experienced dog owner. He's been through basic obedience training and excels at learning new tricks. Max requires regular exercise and mental stimulation.",
    image: "https://images.unsplash.com/photo-1589941013453-ec89f33b5e95?w=600&h=600&fit=crop",
    images: [],
    video: "",
    status: "available",
    shelter: {
      _id: "demo-shelter-001",
      name: "Sunny Paws Rescue",
      location: "San Francisco, CA",
    },
  },
  {
    _id: "demo-animal-006",
    name: "Cleo",
    type: "Cats",
    age: 7,
    breed: "Persian",
    sex: "Female",
    color: "White",
    description: "Cleo is a dignified Persian cat who enjoys a peaceful environment. She loves being brushed and will purr contentedly in your lap. Cleo is best suited for a quiet home without young children or energetic dogs.",
    image: "https://images.unsplash.com/photo-1518791841217-8f162f1e1131?w=600&h=600&fit=crop",
    images: [],
    video: "",
    status: "adopted",
    shelter: {
      _id: "demo-shelter-001",
      name: "Sunny Paws Rescue",
      location: "San Francisco, CA",
    },
  },
  {
    _id: "demo-animal-007",
    name: "Rocky",
    type: "Dogs",
    age: 3,
    breed: "Pit Bull Mix",
    sex: "Male",
    color: "Brindle",
    description: "Rocky is a sweet and goofy pit bull mix who loves everyone he meets. Despite his muscular appearance, he's a gentle giant who thinks he's a lap dog. Rocky is great with kids and other dogs.",
    image: "https://images.unsplash.com/photo-1561037404-61cd46aa615b?w=600&h=600&fit=crop",
    images: [],
    video: "",
    status: "available",
    shelter: {
      _id: "demo-shelter-001",
      name: "Sunny Paws Rescue",
      location: "San Francisco, CA",
    },
  },
  {
    _id: "demo-animal-008",
    name: "Shadow",
    type: "Cats",
    age: 2,
    breed: "Domestic Longhair",
    sex: "Male",
    color: "Black",
    description: "Shadow is a sleek black cat with a mysterious charm. He's independent but affectionate once he warms up to you. Shadow enjoys playing with toys and watching birds from the window.",
    image: "https://images.unsplash.com/photo-1557246565-8a3d3ab5d7f6?w=600&h=600&fit=crop",
    images: [],
    video: "",
    status: "available",
    shelter: {
      _id: "demo-shelter-001",
      name: "Sunny Paws Rescue",
      location: "San Francisco, CA",
    },
  },
];

// Demo Applications
export const demoApplications: Application[] = [
  {
    _id: "demo-app-001",
    animalId: "demo-animal-001",
    userId: "demo-user-001",
    applicationData: JSON.stringify({
      firstName: "Emily",
      lastName: "Johnson",
      email: "emily.johnson@email.com",
      phoneNumber: "(415) 555-7890",
      streetAddress: "123 Oak Street",
      city: "San Francisco",
      state: "CA",
      housing: "House",
      housingType: "Own",
      activityLevel: "High",
    }),
    status: "under_review",
    submittedAt: "2025-01-25T14:30:00Z",
    animal: demoAnimals[0],
  },
  {
    _id: "demo-app-002",
    animalId: "demo-animal-003",
    userId: "demo-user-002",
    applicationData: JSON.stringify({
      firstName: "Michael",
      lastName: "Chen",
      email: "m.chen@email.com",
      phoneNumber: "(415) 555-4567",
      streetAddress: "456 Pine Avenue",
      city: "Oakland",
      state: "CA",
      housing: "Apartment",
      housingType: "Rent",
      activityLevel: "Moderate",
    }),
    status: "approved",
    submittedAt: "2025-01-20T10:15:00Z",
    animal: demoAnimals[2],
  },
  {
    _id: "demo-app-003",
    animalId: "demo-animal-002",
    userId: "demo-user-003",
    applicationData: JSON.stringify({
      firstName: "Sarah",
      lastName: "Williams",
      email: "sarah.w@email.com",
      phoneNumber: "(510) 555-1234",
      streetAddress: "789 Maple Drive",
      city: "Berkeley",
      state: "CA",
      housing: "Condo",
      housingType: "Own",
      activityLevel: "Low",
    }),
    status: "submitted",
    submittedAt: "2025-01-28T09:00:00Z",
    animal: demoAnimals[1],
  },
  {
    _id: "demo-app-004",
    animalId: "demo-animal-005",
    userId: "demo-user-004",
    applicationData: JSON.stringify({
      firstName: "David",
      lastName: "Martinez",
      email: "d.martinez@email.com",
      phoneNumber: "(650) 555-9876",
      streetAddress: "321 Cedar Lane",
      city: "Palo Alto",
      state: "CA",
      housing: "House",
      housingType: "Own",
      activityLevel: "High",
    }),
    status: "rejected",
    submittedAt: "2025-01-15T16:45:00Z",
    animal: demoAnimals[4],
  },
];

// Demo Donations
export const demoDonations: Donation[] = [
  {
    _id: "demo-donation-001",
    shelterId: "demo-shelter-001",
    userId: "demo-user-005",
    donorName: "Anonymous",
    amount: 100,
    message: "Keep up the great work!",
    createdAt: "2025-01-28T12:00:00Z",
  },
  {
    _id: "demo-donation-002",
    shelterId: "demo-shelter-001",
    userId: "demo-user-006",
    donorName: "Jennifer Lee",
    amount: 250,
    message: "In memory of my beloved pet Max",
    createdAt: "2025-01-26T15:30:00Z",
  },
  {
    _id: "demo-donation-003",
    shelterId: "demo-shelter-001",
    donorName: "Corporate Sponsor",
    amount: 1000,
    message: "Annual corporate giving program",
    createdAt: "2025-01-20T10:00:00Z",
  },
  {
    _id: "demo-donation-004",
    shelterId: "demo-shelter-001",
    donorName: "Pet Lovers Club",
    amount: 500,
    message: "Fundraiser proceeds",
    createdAt: "2025-01-15T14:00:00Z",
  },
];

// Demo Events
export const demoEvents: ShelterEvent[] = [
  {
    _id: "demo-event-001",
    shelterId: "demo-shelter-001",
    title: "Adoption Day - Meet Our Pups!",
    description: "Come meet our adorable dogs looking for forever homes. Reduced adoption fees all day!",
    date: "2025-02-15T10:00:00Z",
    endDate: "2025-02-15T16:00:00Z",
    location: "Sunny Paws Rescue Main Facility",
    eventType: "adoption_day",
  },
  {
    _id: "demo-event-002",
    shelterId: "demo-shelter-001",
    title: "Cat Cafe Pop-up",
    description: "Enjoy coffee and pastries while meeting our friendly cats. All proceeds support shelter operations.",
    date: "2025-02-22T09:00:00Z",
    endDate: "2025-02-22T14:00:00Z",
    location: "Downtown Community Center",
    eventType: "fundraiser",
  },
  {
    _id: "demo-event-003",
    shelterId: "demo-shelter-001",
    title: "Volunteer Orientation",
    description: "Learn about volunteer opportunities at Sunny Paws Rescue. New volunteers welcome!",
    date: "2025-02-08T13:00:00Z",
    endDate: "2025-02-08T15:00:00Z",
    location: "Sunny Paws Rescue Training Room",
    eventType: "volunteer",
  },
];

// Demo Fosters
export const demoFosters: Foster[] = [
  {
    _id: "demo-foster-001",
    shelterId: "demo-shelter-001",
    animalId: "demo-animal-004",
    userId: "demo-user-007",
    fosterName: "Amanda Peterson",
    fosterEmail: "amanda.p@email.com",
    startDate: "2025-01-10T00:00:00Z",
    status: "active",
    notes: "Mittens is adjusting well. She's very playful in the evenings.",
    createdAt: "2025-01-10T00:00:00Z",
  },
  {
    _id: "demo-foster-002",
    shelterId: "demo-shelter-001",
    animalId: "demo-animal-008",
    userId: "demo-user-008",
    fosterName: "Robert Kim",
    fosterEmail: "r.kim@email.com",
    startDate: "2025-01-05T00:00:00Z",
    status: "active",
    notes: "Shadow is doing great. He's come out of his shell and loves to play.",
    createdAt: "2025-01-05T00:00:00Z",
  },
];

// Demo Volunteers
export const demoVolunteers: Volunteer[] = [
  {
    _id: "demo-volunteer-001",
    shelterId: "demo-shelter-001",
    userId: "demo-user-009",
    name: "Jessica Taylor",
    email: "j.taylor@email.com",
    phone: "(415) 555-3333",
    skills: ["Dog Walking", "Photography", "Social Media"],
    availability: "Weekends",
    status: "active",
    startDate: "2024-06-15T00:00:00Z",
    totalHours: 120,
    notes: "Excellent with shy dogs. Takes great photos for adoption profiles.",
    createdAt: "2024-06-15T00:00:00Z",
  },
  {
    _id: "demo-volunteer-002",
    shelterId: "demo-shelter-001",
    userId: "demo-user-010",
    name: "Carlos Rivera",
    email: "c.rivera@email.com",
    phone: "(415) 555-4444",
    skills: ["Cat Care", "Cleaning", "Event Setup"],
    availability: "Weekday Evenings",
    status: "active",
    startDate: "2024-09-01T00:00:00Z",
    totalHours: 85,
    notes: "Very reliable. Great with cats and kittens.",
    createdAt: "2024-09-01T00:00:00Z",
  },
];

// Demo Behavior Notes
export const demoBehaviorNotes: BehaviorNote[] = [
  {
    _id: "demo-behavior-001",
    animalId: "demo-animal-001",
    shelterId: "demo-shelter-001",
    noteType: "behavior",
    severity: "info",
    content: "Luna shows some excitement around new dogs but calms down quickly. Would benefit from slow introductions.",
    author: "Jessica Taylor",
    resolved: false,
    createdAt: "2025-01-20T10:00:00Z",
  },
  {
    _id: "demo-behavior-002",
    animalId: "demo-animal-005",
    shelterId: "demo-shelter-001",
    noteType: "training",
    severity: "warning",
    content: "Max has some resource guarding with food. Working on 'leave it' command. Feed separately from other dogs.",
    author: "Staff",
    resolved: false,
    createdAt: "2025-01-18T14:30:00Z",
  },
];

// Demo Announcements
export const demoAnnouncements: Announcement[] = [
  {
    _id: "demo-announcement-001",
    shelterId: "demo-shelter-001",
    title: "Winter Weather Protocol",
    content: "Due to cold temperatures, all outdoor activities will be limited. Please ensure all dogs have warm bedding.",
    category: "general",
    author: "Shelter Manager",
    pinned: true,
    active: true,
    createdAt: "2025-01-25T08:00:00Z",
  },
  {
    _id: "demo-announcement-002",
    shelterId: "demo-shelter-001",
    title: "New Kitten Arrivals!",
    content: "We've received 5 new kittens that will be available for adoption next week after their vet checkups.",
    category: "adoption",
    author: "Cat Team Lead",
    pinned: false,
    active: true,
    createdAt: "2025-01-27T12:00:00Z",
  },
];

// Demo Vaccinations
export const demoVaccinations: Vaccination[] = [
  {
    _id: "demo-vax-001",
    animalId: "demo-animal-001",
    shelterId: "demo-shelter-001",
    vaccineName: "Rabies",
    dateAdministered: "2024-12-15T00:00:00Z",
    nextDueDate: "2025-12-15T00:00:00Z",
    veterinarian: "Dr. Sarah Chen",
    status: "current",
    notes: "3-year vaccine administered",
    createdAt: "2024-12-15T00:00:00Z",
  },
  {
    _id: "demo-vax-002",
    animalId: "demo-animal-001",
    shelterId: "demo-shelter-001",
    vaccineName: "DHPP",
    dateAdministered: "2024-12-15T00:00:00Z",
    nextDueDate: "2025-12-15T00:00:00Z",
    veterinarian: "Dr. Sarah Chen",
    status: "current",
    notes: "Booster given",
    createdAt: "2024-12-15T00:00:00Z",
  },
  {
    _id: "demo-vax-003",
    animalId: "demo-animal-002",
    shelterId: "demo-shelter-001",
    vaccineName: "FVRCP",
    dateAdministered: "2024-11-20T00:00:00Z",
    nextDueDate: "2025-11-20T00:00:00Z",
    veterinarian: "Dr. Michael Rodriguez",
    status: "current",
    notes: "Annual booster",
    createdAt: "2024-11-20T00:00:00Z",
  },
];

// Demo Weight Records
export const demoWeightRecords: WeightRecord[] = [
  {
    _id: "demo-weight-001",
    animalId: "demo-animal-001",
    shelterId: "demo-shelter-001",
    weight: 55,
    unit: "lbs",
    notes: "Healthy weight",
    recordedAt: "2025-01-28T10:00:00Z",
    createdAt: "2025-01-28T10:00:00Z",
  },
  {
    _id: "demo-weight-002",
    animalId: "demo-animal-001",
    shelterId: "demo-shelter-001",
    weight: 54,
    unit: "lbs",
    notes: "Slight decrease - monitoring",
    recordedAt: "2025-01-14T10:00:00Z",
    createdAt: "2025-01-14T10:00:00Z",
  },
  {
    _id: "demo-weight-003",
    animalId: "demo-animal-002",
    shelterId: "demo-shelter-001",
    weight: 12,
    unit: "lbs",
    notes: "Ideal weight for age",
    recordedAt: "2025-01-25T11:00:00Z",
    createdAt: "2025-01-25T11:00:00Z",
  },
];

// Demo Intake Logs
export const demoIntakeLogs: IntakeLog[] = [
  {
    _id: "demo-intake-001",
    animalId: "demo-animal-001",
    shelterId: "demo-shelter-001",
    intakeType: "surrender",
    intakeDate: "2024-10-15T00:00:00Z",
    source: "Owner Surrender - Moving",
    condition: "healthy",
    notes: "Owner moving overseas. Up to date on vaccines. Very friendly.",
    createdBy: "Staff",
    createdAt: "2024-10-15T00:00:00Z",
  },
  {
    _id: "demo-intake-002",
    animalId: "demo-animal-002",
    shelterId: "demo-shelter-001",
    intakeType: "stray",
    intakeDate: "2024-09-20T00:00:00Z",
    source: "Found - Mission District",
    condition: "healthy",
    notes: "Found wandering near Dolores Park. No microchip. Very friendly.",
    createdBy: "Staff",
    createdAt: "2024-09-20T00:00:00Z",
  },
];

// Demo Activity Log
export const demoActivityLog: ActivityLogEntry[] = [
  {
    _id: "demo-activity-001",
    shelterId: "demo-shelter-001",
    action: "Application Submitted",
    entityType: "application",
    entityId: "demo-app-003",
    description: "New adoption application received for Whiskers",
    createdAt: "2025-01-28T09:00:00Z",
  },
  {
    _id: "demo-activity-002",
    shelterId: "demo-shelter-001",
    action: "Status Updated",
    entityType: "animal",
    entityId: "demo-animal-003",
    description: "Buddy's status changed to Pending",
    createdAt: "2025-01-27T15:30:00Z",
  },
  {
    _id: "demo-activity-003",
    shelterId: "demo-shelter-001",
    action: "Donation Received",
    entityType: "donation",
    entityId: "demo-donation-001",
    description: "Received $100 donation from Anonymous",
    createdAt: "2025-01-28T12:00:00Z",
  },
  {
    _id: "demo-activity-004",
    shelterId: "demo-shelter-001",
    action: "Volunteer Logged Hours",
    entityType: "user",
    entityId: "demo-volunteer-001",
    description: "Jessica Taylor logged 4 hours of dog walking",
    createdAt: "2025-01-27T18:00:00Z",
  },
  {
    _id: "demo-activity-005",
    shelterId: "demo-shelter-001",
    action: "Medical Record Added",
    entityType: "animal",
    entityId: "demo-animal-001",
    description: "Vaccination record added for Luna",
    createdAt: "2024-12-15T14:00:00Z",
  },
];

// Demo Analytics
export const demoAnalytics = {
  totalAnimals: 8,
  availableAnimals: 5,
  pendingAnimals: 1,
  adoptedAnimals: 2,
  adoptionRate: 25,
  totalApplications: 4,
  submittedApplications: 1,
  underReviewApplications: 1,
  approvedApplications: 1,
  rejectedApplications: 1,
  recentApplications: 3,
  monthlyAdoptions: [
    { month: "Sep", count: 8 },
    { month: "Oct", count: 12 },
    { month: "Nov", count: 15 },
    { month: "Dec", count: 10 },
    { month: "Jan", count: 7 },
  ],
  donationTotal: 1850,
  volunteerHours: 205,
};
