import User from './User';
import Animal from './Animal';
import Application from './Application';
import Shelter from './Shelter';
import SuccessStory from './SuccessStory';
import Review from './Review';
import Notification from './Notification';
import Event from './Event';
import Donation from './Donation';
import Foster from './Foster';
import SavedSearch from './SavedSearch';
import ApplicationTemplate from './ApplicationTemplate';
import ActivityLog from './ActivityLog';
import TerminalReader from './TerminalReader';
import Message from './Message';
import Volunteer from './Volunteer';
import BehaviorNote from './BehaviorNote';
import Announcement from './Announcement';
import Microchip from './Microchip';
import WeightRecord from './WeightRecord';
import Vaccination from './Vaccination';
import AdoptionFee from './AdoptionFee';
import SpayNeuter from './SpayNeuter';
import IntakeLog from './IntakeLog';
import OutcomeLog from './OutcomeLog';
import AuthSession from './AuthSession';
import StatusHistory from './StatusHistory';
import MediaAsset from './MediaAsset';
import DashboardLayout from './DashboardLayout';
import StaffInvitation from './StaffInvitation';
import ShelterStaffRole from './ShelterStaffRole';
import InternalNote from './InternalNote';
import KennelAssignment from './KennelAssignment';
import ShelterSettings from './ShelterSettings';
import ApplicationReview from './ApplicationReview';
import RejectionTemplate from './RejectionTemplate';
import AdopterProfile from './AdopterProfile';
import MatchRecord from './MatchRecord';
import AdoptionRecord from './AdoptionRecord';
import PostAdoptionSurvey from './PostAdoptionSurvey';
import FosterProfile from './FosterProfile';
import FosterPlacement from './FosterPlacement';
import FosterUpdate from './FosterUpdate';
import MessageThread from './MessageThread';
import MessageTemplate from './MessageTemplate';

export { User, Animal, Application, Shelter, SuccessStory, Review, Notification, Event, Donation, Foster, SavedSearch, ApplicationTemplate, ActivityLog, TerminalReader, Message, Volunteer, BehaviorNote, Announcement, Microchip, WeightRecord, Vaccination, AdoptionFee, SpayNeuter, IntakeLog, OutcomeLog, AuthSession, StatusHistory, MediaAsset, DashboardLayout, StaffInvitation, ShelterStaffRole, InternalNote, KennelAssignment, ShelterSettings, ApplicationReview, RejectionTemplate, AdopterProfile, MatchRecord, AdoptionRecord, PostAdoptionSurvey, FosterProfile, FosterPlacement, FosterUpdate, MessageThread, MessageTemplate };

// Also import models to ensure they are registered with Mongoose
import './User';
import './Animal';
import './Application';
import './Shelter';
import './SuccessStory';
import './Review';
import './Notification';
import './Event';
import './Donation';
import './Foster';
import './SavedSearch';
import './ApplicationTemplate';
import './ActivityLog';
import './TerminalReader';
import './Message';
import './Volunteer';
import './BehaviorNote';
import './Announcement';
import './Microchip';
import './WeightRecord';
import './Vaccination';
import './AdoptionFee';
import './SpayNeuter';
import './IntakeLog';
import './OutcomeLog';
import './AuthSession';
import './StatusHistory';
import './MediaAsset';
import './DashboardLayout';
import './StaffInvitation';
import './ShelterStaffRole';
import './InternalNote';
import './KennelAssignment';
import './ShelterSettings';
import './ApplicationReview';
import './RejectionTemplate';
import './AdopterProfile';
import './MatchRecord';
import './AdoptionRecord';
import './PostAdoptionSurvey';
import './FosterProfile';
import './FosterPlacement';
import './FosterUpdate';
import './MessageThread';
import './MessageTemplate';
